version: "2"
linters:
  default: all
  disable:
    - wsl # The linter 'wsl' is deprecated (since v2.2.0) due to: new major version. Replaced by wsl_v5
    - paralleltest # not used in this project
    - revive # temporarily disable
    - errcheck
    - forbidigo
    - gocritic
    - godoclint
    - gosec
  settings:
    depguard:
      rules:
        main:
          list-mode: strict
          allow:
            - bytes
            - context
            - errors
            - fmt
            - io
            - log
            - os
            - path/filepath
            - sort
            - strings
            - testing
            - time
            - github.com/spf13/cobra
            - github.com/spf13/afero
            - gopkg.in/yaml.v3
            - backup-rsync/backup/internal
            - backup-rsync/backup/cmd
    errcheck:
      check-type-assertions: true
      check-blank: true
    varnamelen:
      ignore-decls:
        - fs afero.Fs
formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: true
