version: "2"
linters:
  default: all
  disable:
    - wsl # The linter 'wsl' is deprecated (since v2.2.0) due to: new major version. Replaced by wsl_v5
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    staticcheck:
      checks: all
formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: true
