// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package internal_test

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockExec creates a new instance of MockExec. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExec(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExec {
	mock := &MockExec{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockExec is an autogenerated mock type for the Exec type
type MockExec struct {
	mock.Mock
}

type MockExec_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExec) EXPECT() *MockExec_Expecter {
	return &MockExec_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockExec
func (_mock *MockExec) Execute(name string, args ...string) ([]byte, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(name, args)
	} else {
		tmpRet = _mock.Called(name)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, ...string) ([]byte, error)); ok {
		return returnFunc(name, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, ...string) []byte); ok {
		r0 = returnFunc(name, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, ...string) error); ok {
		r1 = returnFunc(name, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExec_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockExec_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - name string
//   - args ...string
func (_e *MockExec_Expecter) Execute(name interface{}, args ...interface{}) *MockExec_Execute_Call {
	return &MockExec_Execute_Call{Call: _e.mock.On("Execute",
		append([]interface{}{name}, args...)...)}
}

func (_c *MockExec_Execute_Call) Run(run func(name string, args ...string)) *MockExec_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockExec_Execute_Call) Return(bytes []byte, err error) *MockExec_Execute_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockExec_Execute_Call) RunAndReturn(run func(name string, args ...string) ([]byte, error)) *MockExec_Execute_Call {
	_c.Call.Return(run)
	return _c
}
