// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package internal_test

import (
	"backup-rsync/backup/internal"
	"log"

	mock "github.com/stretchr/testify/mock"
)

// NewMockJobCommand creates a new instance of MockJobCommand. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobCommand(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobCommand {
	mock := &MockJobCommand{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJobCommand is an autogenerated mock type for the JobCommand type
type MockJobCommand struct {
	mock.Mock
}

type MockJobCommand_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJobCommand) EXPECT() *MockJobCommand_Expecter {
	return &MockJobCommand_Expecter{mock: &_m.Mock}
}

// GetVersionInfo provides a mock function for the type MockJobCommand
func (_mock *MockJobCommand) GetVersionInfo() (string, string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetVersionInfo")
	}

	var r0 string
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func() (string, string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() string); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func() error); ok {
		r2 = returnFunc()
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockJobCommand_GetVersionInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVersionInfo'
type MockJobCommand_GetVersionInfo_Call struct {
	*mock.Call
}

// GetVersionInfo is a helper method to define mock.On call
func (_e *MockJobCommand_Expecter) GetVersionInfo() *MockJobCommand_GetVersionInfo_Call {
	return &MockJobCommand_GetVersionInfo_Call{Call: _e.mock.On("GetVersionInfo")}
}

func (_c *MockJobCommand_GetVersionInfo_Call) Run(run func()) *MockJobCommand_GetVersionInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockJobCommand_GetVersionInfo_Call) Return(s string, s1 string, err error) *MockJobCommand_GetVersionInfo_Call {
	_c.Call.Return(s, s1, err)
	return _c
}

func (_c *MockJobCommand_GetVersionInfo_Call) RunAndReturn(run func() (string, string, error)) *MockJobCommand_GetVersionInfo_Call {
	_c.Call.Return(run)
	return _c
}

// ReportJobStatus provides a mock function for the type MockJobCommand
func (_mock *MockJobCommand) ReportJobStatus(jobName string, status internal.JobStatus, logger *log.Logger) {
	_mock.Called(jobName, status, logger)
	return
}

// MockJobCommand_ReportJobStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReportJobStatus'
type MockJobCommand_ReportJobStatus_Call struct {
	*mock.Call
}

// ReportJobStatus is a helper method to define mock.On call
//   - jobName string
//   - status internal.JobStatus
//   - logger *log.Logger
func (_e *MockJobCommand_Expecter) ReportJobStatus(jobName interface{}, status interface{}, logger interface{}) *MockJobCommand_ReportJobStatus_Call {
	return &MockJobCommand_ReportJobStatus_Call{Call: _e.mock.On("ReportJobStatus", jobName, status, logger)}
}

func (_c *MockJobCommand_ReportJobStatus_Call) Run(run func(jobName string, status internal.JobStatus, logger *log.Logger)) *MockJobCommand_ReportJobStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 internal.JobStatus
		if args[1] != nil {
			arg1 = args[1].(internal.JobStatus)
		}
		var arg2 *log.Logger
		if args[2] != nil {
			arg2 = args[2].(*log.Logger)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockJobCommand_ReportJobStatus_Call) Return() *MockJobCommand_ReportJobStatus_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockJobCommand_ReportJobStatus_Call) RunAndReturn(run func(jobName string, status internal.JobStatus, logger *log.Logger)) *MockJobCommand_ReportJobStatus_Call {
	_c.Run(run)
	return _c
}

// ReportSummary provides a mock function for the type MockJobCommand
func (_mock *MockJobCommand) ReportSummary(counts map[internal.JobStatus]int, logger *log.Logger) {
	_mock.Called(counts, logger)
	return
}

// MockJobCommand_ReportSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReportSummary'
type MockJobCommand_ReportSummary_Call struct {
	*mock.Call
}

// ReportSummary is a helper method to define mock.On call
//   - counts map[internal.JobStatus]int
//   - logger *log.Logger
func (_e *MockJobCommand_Expecter) ReportSummary(counts interface{}, logger interface{}) *MockJobCommand_ReportSummary_Call {
	return &MockJobCommand_ReportSummary_Call{Call: _e.mock.On("ReportSummary", counts, logger)}
}

func (_c *MockJobCommand_ReportSummary_Call) Run(run func(counts map[internal.JobStatus]int, logger *log.Logger)) *MockJobCommand_ReportSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 map[internal.JobStatus]int
		if args[0] != nil {
			arg0 = args[0].(map[internal.JobStatus]int)
		}
		var arg1 *log.Logger
		if args[1] != nil {
			arg1 = args[1].(*log.Logger)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJobCommand_ReportSummary_Call) Return() *MockJobCommand_ReportSummary_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockJobCommand_ReportSummary_Call) RunAndReturn(run func(counts map[internal.JobStatus]int, logger *log.Logger)) *MockJobCommand_ReportSummary_Call {
	_c.Run(run)
	return _c
}

// Run provides a mock function for the type MockJobCommand
func (_mock *MockJobCommand) Run(job internal.Job) internal.JobStatus {
	ret := _mock.Called(job)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 internal.JobStatus
	if returnFunc, ok := ret.Get(0).(func(internal.Job) internal.JobStatus); ok {
		r0 = returnFunc(job)
	} else {
		r0 = ret.Get(0).(internal.JobStatus)
	}
	return r0
}

// MockJobCommand_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockJobCommand_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - job internal.Job
func (_e *MockJobCommand_Expecter) Run(job interface{}) *MockJobCommand_Run_Call {
	return &MockJobCommand_Run_Call{Call: _e.mock.On("Run", job)}
}

func (_c *MockJobCommand_Run_Call) Run(run func(job internal.Job)) *MockJobCommand_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 internal.Job
		if args[0] != nil {
			arg0 = args[0].(internal.Job)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJobCommand_Run_Call) Return(jobStatus internal.JobStatus) *MockJobCommand_Run_Call {
	_c.Call.Return(jobStatus)
	return _c
}

func (_c *MockJobCommand_Run_Call) RunAndReturn(run func(job internal.Job) internal.JobStatus) *MockJobCommand_Run_Call {
	_c.Call.Return(run)
	return _c
}
